---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sops.stuttgart-things.com
  resources:
  - gitrepositories
  - sopssecretmanifests
  - sopssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sops.stuttgart-things.com
  resources:
  - gitrepositories/finalizers
  - sopssecretmanifests/finalizers
  - sopssecrets/finalizers
  verbs:
  - update
- apiGroups:
  - sops.stuttgart-things.com
  resources:
  - gitrepositories/status
  - sopssecretmanifests/status
  - sopssecrets/status
  verbs:
  - get
  - patch
  - update
