## Append samples of your project ##
resources:
- sops_v1alpha1_gitrepository.yaml
- sops_v1alpha1_sopssecret.yaml
- sops_v1alpha1_sopssecretmanifest.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
