apiVersion: sops.stuttgart-things.com/v1alpha1
kind: SopsSecretManifest
metadata:
  labels:
    app.kubernetes.io/name: sops-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: sopssecretmanifest-sample
spec:
  # TODO(user): Add fields here
